#Tomcat
server:
  port: 8080
# DataSource
spring:
  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: "GMT+8"
  datasource:
    dynamic:
      primary: tiptop
      strict: false
      datasource:
        tiptop:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.16.200.40:1521/topprod
          username: wctz
          password: wctz
        ly:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/eoms?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: root
        flux wms:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://172.17.200.149:1433;DatabaseName=WMS_FTEST
          username: JX2001001
          password: JX2001001
        flux wcs:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.200.153:3306/wcsdb?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: fluxwcs123
        flux rcs:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.200.154:3306/mr_rcs?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: mr123
mybatis:
  type-aliases-package: com.keboda.eomsback.*.pojo
  mapper-locations: classpath:mapping/*/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

page helper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  auto-runtime-dialect: true


logging:
  level:
    com.keboda.eomsback.* : DEBUG