#Tomcat
server:
  port: 18080
# DataSource
spring:
  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: "GMT+8"
  datasource:
    dynamic:
      primary: tiptop
      strict: false
      datasource:
        tiptop:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@172.16.200.40:1521/topprod
          username: wctz
          password: wctz
        fluxWms:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://172.17.200.156:1433;DatabaseName=WMS_PROD
          username: WMS_PROD
          password: WMS_PROD#@￥
        fluxWcs:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.200.153:3306/wcsdb?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: fluxwcs123
        fluxRcs:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.200.154:3306/mr_rcs?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: mr123
mybatis:
  type-aliases-package: com.keboda.eomsback.*.pojo
  mapper-locations: classpath:mapping/*/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

page helper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  auto-runtime-dialect: true

#自定义定时器动态执行
timer:
  rcsRobotsTimer:
    corn: 0 0/5 * * * ?
  InvalidDocumentDeleteTimer:
    corn: 0 59 23 1 * ?
