#Tomcat
server:
  port: 8080
# DataSource
spring:
  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: "GMT+8"
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.16.200.40:1521/topprod
          username: wctz
          password: wctz
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.171.23:3306/eoms?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: root
        flux:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://172.17.200.156:1433;DatabaseName=WMS_PROD
          username: WMS_PROD
          password: WMS_PROD#@￥

mybatis:
  type-aliases-package: com.keboda.eomsback.*.pojo
  mapper-locations: classpath:mapping/*/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

page helper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  auto-runtime-dialect: true

logging:
  level:
    com.keboda.eomsback.* : DEBUG

